#include "lotto_catalog.h"

/*
 * LD(10,5,4,3;7).
 *
 * The construction uses the Klein four-group generated by
 *
 *   g = (0 1)(2 3)(4 5)
 *   h = (0 2)(1 3)(6 7)
 *
 * on X = {0,...,9}.  The three base blocks have orbit sizes 4, 2 and 1.
 * The core expander does not rely on the special relations g^2 = h^2 = 1
 * or gh = hg; it computes the closure under the supplied generators.
 */

static const lotto_block_t lotto_10_5_4_3_base_blocks[] = {
    { 5U, { 0U, 1U, 2U, 4U, 8U } },
    { 5U, { 0U, 2U, 6U, 7U, 9U } },
    { 5U, { 4U, 5U, 6U, 7U, 9U } }
};

static const lotto_permutation_t lotto_10_5_4_3_generators[] = {
    {
        { 1U, 0U, 3U, 2U, 5U, 4U, 6U, 7U, 8U, 9U,
          10U, 11U, 12U, 13U, 14U, 15U, 16U, 17U, 18U, 19U }
    },
    {
        { 2U, 3U, 0U, 1U, 4U, 5U, 7U, 6U, 8U, 9U,
          10U, 11U, 12U, 13U, 14U, 15U, 16U, 17U, 18U, 19U }
    }
};

static const unsigned int lotto_10_5_4_3_orbit_sizes[] = {
    4U, 2U, 1U
};

const lotto_construction_t lotto_construction_10_5_4_3 = {
    "LD(10,5,4,3;7)",
    { 10U, 5U, 4U, 3U },
    lotto_10_5_4_3_base_blocks,
    sizeof(lotto_10_5_4_3_base_blocks) /
        sizeof(lotto_10_5_4_3_base_blocks[0]),
    lotto_10_5_4_3_generators,
    sizeof(lotto_10_5_4_3_generators) /
        sizeof(lotto_10_5_4_3_generators[0]),
    lotto_10_5_4_3_orbit_sizes,
    7U
};
